"""core: broadcast_state

Revision ID: b51796b3511b
Revises: 7b984cc6dcba
Create Date: 2026-07-19 00:48:35.651385

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'b51796b3511b'
down_revision: str | None = '7b984cc6dcba'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcast_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('active_encounter_id', sa.Integer(), nullable=True),
    sa.Column('active_map_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcast_state_campaign_id'), 'broadcast_state', ['campaign_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_broadcast_state_campaign_id'), table_name='broadcast_state')
    op.drop_table('broadcast_state')
    # ### end Alembic commands ###
