"""dice: saved_roll and roll_history

Revision ID: a0395aa795f0
Revises: b51796b3511b
Create Date: 2026-07-19 02:05:04.135342

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'a0395aa795f0'
down_revision: str | None = 'b51796b3511b'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roll_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('expression', sa.String(length=200), nullable=False),
    sa.Column('result', sa.Integer(), nullable=False),
    sa.Column('breakdown_json', sa.Text(), nullable=False),
    sa.Column('rolled_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roll_history_campaign_id'), 'roll_history', ['campaign_id'], unique=False)
    op.create_table('saved_roll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('expression', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_roll_campaign_id'), 'saved_roll', ['campaign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_roll_campaign_id'), table_name='saved_roll')
    op.drop_table('saved_roll')
    op.drop_index(op.f('ix_roll_history_campaign_id'), table_name='roll_history')
    op.drop_table('roll_history')
    # ### end Alembic commands ###
