"""factions: faction, faction_clock, faction_activity

Revision ID: 04887ed61ed8
Revises: 4f631f5dd48b
Create Date: 2026-07-19 14:26:42.819057

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '04887ed61ed8'
down_revision: str | None = '4f631f5dd48b'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('disposition', sa.String(length=20), server_default='neutral', nullable=False),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faction_campaign_id'), 'faction', ['campaign_id'], unique=False)
    op.create_table('faction_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faction_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('entry', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['faction.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faction_activity_faction_id'), 'faction_activity', ['faction_id'], unique=False)
    op.create_table('faction_clock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faction_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('segments', sa.Integer(), server_default='6', nullable=False),
    sa.Column('filled', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['faction.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faction_clock_faction_id'), 'faction_clock', ['faction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faction_clock_faction_id'), table_name='faction_clock')
    op.drop_table('faction_clock')
    op.drop_index(op.f('ix_faction_activity_faction_id'), table_name='faction_activity')
    op.drop_table('faction_activity')
    op.drop_index(op.f('ix_faction_campaign_id'), table_name='faction')
    op.drop_table('faction')
    # ### end Alembic commands ###
