"""npcs: npc

Revision ID: 47c16b0d6685
Revises: 04887ed61ed8
Create Date: 2026-07-19 19:38:07.751402

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '47c16b0d6685'
down_revision: str | None = '04887ed61ed8'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('npc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('statblock', sa.Text(), nullable=True),
    sa.Column('motivation', sa.Text(), nullable=True),
    sa.Column('secrets', sa.Text(), nullable=True),
    sa.Column('voice', sa.Text(), nullable=True),
    sa.Column('portrait_path', sa.String(length=255), nullable=True),
    sa.Column('faction_id', sa.Integer(), nullable=True),
    sa.Column('disposition', sa.String(length=20), server_default='neutral', nullable=False),
    sa.Column('player_visible', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_npc_campaign_id'), 'npc', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_npc_faction_id'), 'npc', ['faction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_npc_faction_id'), table_name='npc')
    op.drop_index(op.f('ix_npc_campaign_id'), table_name='npc')
    op.drop_table('npc')
    # ### end Alembic commands ###
