"""wiki: wiki_page, wiki_link, tag, wiki_page_tag

Revision ID: 4e8e0f2997c9
Revises: 47c16b0d6685
Create Date: 2026-07-19 23:45:08.943337

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '4e8e0f2997c9'
down_revision: str | None = '47c16b0d6685'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'name', name='uq_tag_campaign_name')
    )
    op.create_index(op.f('ix_tag_campaign_id'), 'tag', ['campaign_id'], unique=False)
    op.create_table('wiki_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('player_visible', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'slug', name='uq_wiki_page_campaign_slug')
    )
    op.create_index(op.f('ix_wiki_page_campaign_id'), 'wiki_page', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_wiki_page_category'), 'wiki_page', ['category'], unique=False)
    op.create_table('wiki_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_page_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_title', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['source_page_id'], ['wiki_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wiki_link_source_page_id'), 'wiki_link', ['source_page_id'], unique=False)
    op.create_index(op.f('ix_wiki_link_target_id'), 'wiki_link', ['target_id'], unique=False)
    op.create_table('wiki_page_tag',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['wiki_page.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('page_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wiki_page_tag')
    op.drop_index(op.f('ix_wiki_link_target_id'), table_name='wiki_link')
    op.drop_index(op.f('ix_wiki_link_source_page_id'), table_name='wiki_link')
    op.drop_table('wiki_link')
    op.drop_index(op.f('ix_wiki_page_category'), table_name='wiki_page')
    op.drop_index(op.f('ix_wiki_page_campaign_id'), table_name='wiki_page')
    op.drop_table('wiki_page')
    op.drop_index(op.f('ix_tag_campaign_id'), table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
