"""combat encounter combatant

Revision ID: 4a9378888d34
Revises: 4e8e0f2997c9
Create Date: 2026-07-20 23:00:41.197177

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4a9378888d34"
down_revision: str | None = "4e8e0f2997c9"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "encounter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("round", sa.Integer(), server_default="1", nullable=False),
        sa.Column("active_combatant_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_encounter_campaign_id"), "encounter", ["campaign_id"], unique=False)
    op.create_table(
        "combatant",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("encounter_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("initiative", sa.Integer(), server_default="0", nullable=False),
        sa.Column("hp_current", sa.Integer(), server_default="0", nullable=False),
        sa.Column("hp_max", sa.Integer(), server_default="0", nullable=False),
        sa.Column("ac", sa.Integer(), nullable=True),
        sa.Column("conditions_json", sa.Text(), server_default="[]", nullable=False),
        sa.Column("concentration", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_pc", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("visible_to_players", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("npc_id", sa.Integer(), nullable=True),
        sa.Column("token_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["encounter_id"], ["encounter.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_combatant_encounter_id"), "combatant", ["encounter_id"], unique=False)
    op.create_index(op.f("ix_combatant_npc_id"), "combatant", ["npc_id"], unique=False)
    op.create_index(op.f("ix_combatant_token_id"), "combatant", ["token_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_combatant_token_id"), table_name="combatant")
    op.drop_index(op.f("ix_combatant_npc_id"), table_name="combatant")
    op.drop_index(op.f("ix_combatant_encounter_id"), table_name="combatant")
    op.drop_table("combatant")
    op.drop_index(op.f("ix_encounter_campaign_id"), table_name="encounter")
    op.drop_table("encounter")
    # ### end Alembic commands ###
