"""maps map token fog_region

Revision ID: 37c79f8af31d
Revises: 4a9378888d34
Create Date: 2026-07-21 01:17:46.802718

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "37c79f8af31d"
down_revision: str | None = "4a9378888d34"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "map",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("image_path", sa.String(length=500), nullable=True),
        sa.Column("image_w", sa.Integer(), nullable=True),
        sa.Column("image_h", sa.Integer(), nullable=True),
        sa.Column("grid_size_px", sa.Integer(), server_default="70", nullable=False),
        sa.Column("grid_offset_x", sa.Integer(), server_default="0", nullable=False),
        sa.Column("grid_offset_y", sa.Integer(), server_default="0", nullable=False),
        sa.Column("grid_visible", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("feet_per_square", sa.Integer(), server_default="5", nullable=False),
        sa.Column(
            "diagonal_rule", sa.String(length=20), server_default="chebyshev", nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_map_campaign_id"), "map", ["campaign_id"], unique=False)
    op.create_table(
        "fog_region",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("map_id", sa.Integer(), nullable=False),
        sa.Column("order_index", sa.Integer(), server_default="0", nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("geometry_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["map_id"], ["map.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fog_region_map_id"), "fog_region", ["map_id"], unique=False)
    op.create_table(
        "token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("map_id", sa.Integer(), nullable=False),
        sa.Column("layer", sa.String(length=20), server_default="tokens", nullable=False),
        sa.Column("kind", sa.String(length=20), server_default="disc", nullable=False),
        sa.Column("x", sa.Integer(), server_default="0", nullable=False),
        sa.Column("y", sa.Integer(), server_default="0", nullable=False),
        sa.Column("size_squares", sa.Integer(), server_default="1", nullable=False),
        sa.Column("color", sa.String(length=20), server_default="#888888", nullable=False),
        sa.Column("image_path", sa.String(length=500), nullable=True),
        sa.Column("name", sa.String(length=200), server_default="", nullable=False),
        sa.Column("hp_current", sa.Integer(), nullable=True),
        sa.Column("hp_max", sa.Integer(), nullable=True),
        sa.Column("hp_visible_to_players", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("visible_to_players", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("status_markers_json", sa.Text(), server_default="[]", nullable=False),
        sa.Column("is_pc", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("npc_id", sa.Integer(), nullable=True),
        sa.Column("combatant_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["map_id"], ["map.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_token_combatant_id"), "token", ["combatant_id"], unique=False)
    op.create_index(op.f("ix_token_map_id"), "token", ["map_id"], unique=False)
    op.create_index(op.f("ix_token_npc_id"), "token", ["npc_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_token_npc_id"), table_name="token")
    op.drop_index(op.f("ix_token_map_id"), table_name="token")
    op.drop_index(op.f("ix_token_combatant_id"), table_name="token")
    op.drop_table("token")
    op.drop_index(op.f("ix_fog_region_map_id"), table_name="fog_region")
    op.drop_table("fog_region")
    op.drop_index(op.f("ix_map_campaign_id"), table_name="map")
    op.drop_table("map")
    # ### end Alembic commands ###
