"""maps map token fog_region

Revision ID: 37c79f8af31d
Revises: 4a9378888d34
Create Date: 2026-07-21 01:17:46.802718

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "37c79f8af31d"
down_revision: str | None = "4a9378888d34"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_setting",
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "campaign",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "broadcast_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("active_encounter_id", sa.Integer(), nullable=True),
        sa.Column("active_map_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_broadcast_state_campaign_id"), "broadcast_state", ["campaign_id"], unique=True
    )
    op.create_table(
        "encounter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("round", sa.Integer(), server_default="1", nullable=False),
        sa.Column("active_combatant_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_encounter_campaign_id"), "encounter", ["campaign_id"], unique=False)
    op.create_table(
        "faction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("disposition", sa.String(length=20), server_default="neutral", nullable=False),
        sa.Column("goals", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_faction_campaign_id"), "faction", ["campaign_id"], unique=False)
    op.create_table(
        "map",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("image_path", sa.String(length=500), nullable=True),
        sa.Column("image_w", sa.Integer(), nullable=True),
        sa.Column("image_h", sa.Integer(), nullable=True),
        sa.Column("grid_size_px", sa.Integer(), server_default="70", nullable=False),
        sa.Column("grid_offset_x", sa.Integer(), server_default="0", nullable=False),
        sa.Column("grid_offset_y", sa.Integer(), server_default="0", nullable=False),
        sa.Column("grid_visible", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("feet_per_square", sa.Integer(), server_default="5", nullable=False),
        sa.Column(
            "diagonal_rule", sa.String(length=20), server_default="chebyshev", nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_map_campaign_id"), "map", ["campaign_id"], unique=False)
    op.create_table(
        "npc",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("statblock", sa.Text(), nullable=True),
        sa.Column("motivation", sa.Text(), nullable=True),
        sa.Column("secrets", sa.Text(), nullable=True),
        sa.Column("voice", sa.Text(), nullable=True),
        sa.Column("portrait_path", sa.String(length=255), nullable=True),
        sa.Column("faction_id", sa.Integer(), nullable=True),
        sa.Column("disposition", sa.String(length=20), server_default="neutral", nullable=False),
        sa.Column("player_visible", sa.Boolean(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_npc_campaign_id"), "npc", ["campaign_id"], unique=False)
    op.create_index(op.f("ix_npc_faction_id"), "npc", ["faction_id"], unique=False)
    op.create_table(
        "roll_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("expression", sa.String(length=200), nullable=False),
        sa.Column("result", sa.Integer(), nullable=False),
        sa.Column("breakdown_json", sa.Text(), nullable=False),
        sa.Column(
            "rolled_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_roll_history_campaign_id"), "roll_history", ["campaign_id"], unique=False
    )
    op.create_table(
        "saved_roll",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("expression", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_saved_roll_campaign_id"), "saved_roll", ["campaign_id"], unique=False)
    op.create_table(
        "session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="planned", nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_session_campaign_id"), "session", ["campaign_id"], unique=False)
    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campaign_id", "name", name="uq_tag_campaign_name"),
    )
    op.create_index(op.f("ix_tag_campaign_id"), "tag", ["campaign_id"], unique=False)
    op.create_table(
        "wiki_page",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=220), nullable=False),
        sa.Column("body_md", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=80), nullable=True),
        sa.Column("player_visible", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campaign_id", "slug", name="uq_wiki_page_campaign_slug"),
    )
    op.create_index(op.f("ix_wiki_page_campaign_id"), "wiki_page", ["campaign_id"], unique=False)
    op.create_index(op.f("ix_wiki_page_category"), "wiki_page", ["category"], unique=False)
    op.create_table(
        "combatant",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("encounter_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("initiative", sa.Integer(), server_default="0", nullable=False),
        sa.Column("hp_current", sa.Integer(), server_default="0", nullable=False),
        sa.Column("hp_max", sa.Integer(), server_default="0", nullable=False),
        sa.Column("ac", sa.Integer(), nullable=True),
        sa.Column("conditions_json", sa.Text(), server_default="[]", nullable=False),
        sa.Column("concentration", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_pc", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("visible_to_players", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("npc_id", sa.Integer(), nullable=True),
        sa.Column("token_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["encounter_id"], ["encounter.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_combatant_encounter_id"), "combatant", ["encounter_id"], unique=False)
    op.create_index(op.f("ix_combatant_npc_id"), "combatant", ["npc_id"], unique=False)
    op.create_index(op.f("ix_combatant_token_id"), "combatant", ["token_id"], unique=False)
    op.create_table(
        "faction_activity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("faction_id", sa.Integer(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("entry", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["faction_id"], ["faction.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_faction_activity_faction_id"), "faction_activity", ["faction_id"], unique=False
    )
    op.create_table(
        "faction_clock",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("faction_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("segments", sa.Integer(), server_default="6", nullable=False),
        sa.Column("filled", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["faction_id"], ["faction.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_faction_clock_faction_id"), "faction_clock", ["faction_id"], unique=False
    )
    op.create_table(
        "fog_region",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("map_id", sa.Integer(), nullable=False),
        sa.Column("order_index", sa.Integer(), server_default="0", nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("geometry_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["map_id"], ["map.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fog_region_map_id"), "fog_region", ["map_id"], unique=False)
    op.create_table(
        "session_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column(
            "logged_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("tag", sa.String(length=20), server_default="none", nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["session.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_session_log_session_id"), "session_log", ["session_id"], unique=False)
    op.create_table(
        "token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("map_id", sa.Integer(), nullable=False),
        sa.Column("layer", sa.String(length=20), server_default="tokens", nullable=False),
        sa.Column("kind", sa.String(length=20), server_default="disc", nullable=False),
        sa.Column("x", sa.Integer(), server_default="0", nullable=False),
        sa.Column("y", sa.Integer(), server_default="0", nullable=False),
        sa.Column("size_squares", sa.Integer(), server_default="1", nullable=False),
        sa.Column("color", sa.String(length=20), server_default="#888888", nullable=False),
        sa.Column("image_path", sa.String(length=500), nullable=True),
        sa.Column("name", sa.String(length=200), server_default="", nullable=False),
        sa.Column("hp_current", sa.Integer(), nullable=True),
        sa.Column("hp_max", sa.Integer(), nullable=True),
        sa.Column("hp_visible_to_players", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("visible_to_players", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("status_markers_json", sa.Text(), server_default="[]", nullable=False),
        sa.Column("is_pc", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("npc_id", sa.Integer(), nullable=True),
        sa.Column("combatant_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["map_id"], ["map.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_token_combatant_id"), "token", ["combatant_id"], unique=False)
    op.create_index(op.f("ix_token_map_id"), "token", ["map_id"], unique=False)
    op.create_index(op.f("ix_token_npc_id"), "token", ["npc_id"], unique=False)
    op.create_table(
        "wiki_link",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_page_id", sa.Integer(), nullable=False),
        sa.Column("target_type", sa.String(length=20), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=True),
        sa.Column("target_title", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_page_id"],
            ["wiki_page.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wiki_link_source_page_id"), "wiki_link", ["source_page_id"], unique=False
    )
    op.create_index(op.f("ix_wiki_link_target_id"), "wiki_link", ["target_id"], unique=False)
    op.create_table(
        "wiki_page_tag",
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["wiki_page.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
        ),
        sa.PrimaryKeyConstraint("page_id", "tag_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wiki_page_tag")
    op.drop_index(op.f("ix_wiki_link_target_id"), table_name="wiki_link")
    op.drop_index(op.f("ix_wiki_link_source_page_id"), table_name="wiki_link")
    op.drop_table("wiki_link")
    op.drop_index(op.f("ix_token_npc_id"), table_name="token")
    op.drop_index(op.f("ix_token_map_id"), table_name="token")
    op.drop_index(op.f("ix_token_combatant_id"), table_name="token")
    op.drop_table("token")
    op.drop_index(op.f("ix_session_log_session_id"), table_name="session_log")
    op.drop_table("session_log")
    op.drop_index(op.f("ix_fog_region_map_id"), table_name="fog_region")
    op.drop_table("fog_region")
    op.drop_index(op.f("ix_faction_clock_faction_id"), table_name="faction_clock")
    op.drop_table("faction_clock")
    op.drop_index(op.f("ix_faction_activity_faction_id"), table_name="faction_activity")
    op.drop_table("faction_activity")
    op.drop_index(op.f("ix_combatant_token_id"), table_name="combatant")
    op.drop_index(op.f("ix_combatant_npc_id"), table_name="combatant")
    op.drop_index(op.f("ix_combatant_encounter_id"), table_name="combatant")
    op.drop_table("combatant")
    op.drop_index(op.f("ix_wiki_page_category"), table_name="wiki_page")
    op.drop_index(op.f("ix_wiki_page_campaign_id"), table_name="wiki_page")
    op.drop_table("wiki_page")
    op.drop_index(op.f("ix_tag_campaign_id"), table_name="tag")
    op.drop_table("tag")
    op.drop_index(op.f("ix_session_campaign_id"), table_name="session")
    op.drop_table("session")
    op.drop_index(op.f("ix_saved_roll_campaign_id"), table_name="saved_roll")
    op.drop_table("saved_roll")
    op.drop_index(op.f("ix_roll_history_campaign_id"), table_name="roll_history")
    op.drop_table("roll_history")
    op.drop_index(op.f("ix_npc_faction_id"), table_name="npc")
    op.drop_index(op.f("ix_npc_campaign_id"), table_name="npc")
    op.drop_table("npc")
    op.drop_index(op.f("ix_map_campaign_id"), table_name="map")
    op.drop_table("map")
    op.drop_index(op.f("ix_faction_campaign_id"), table_name="faction")
    op.drop_table("faction")
    op.drop_index(op.f("ix_encounter_campaign_id"), table_name="encounter")
    op.drop_table("encounter")
    op.drop_index(op.f("ix_broadcast_state_campaign_id"), table_name="broadcast_state")
    op.drop_table("broadcast_state")
    op.drop_table("campaign")
    op.drop_table("app_setting")
    # ### end Alembic commands ###
