"""bestiary bestiary_monster

Revision ID: ac8a6dd8a6ad
Revises: 37c79f8af31d
Create Date: 2026-07-23 00:43:47.264597

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'ac8a6dd8a6ad'
down_revision: str | None = '37c79f8af31d'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bestiary_monster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('statblock', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('cloned_from_content_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'slug', name='uq_bestiary_monster_campaign_slug')
    )
    op.create_index(op.f('ix_bestiary_monster_campaign_id'), 'bestiary_monster', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_bestiary_monster_cloned_from_content_id'), 'bestiary_monster', ['cloned_from_content_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bestiary_monster_cloned_from_content_id'), table_name='bestiary_monster')
    op.drop_index(op.f('ix_bestiary_monster_campaign_id'), table_name='bestiary_monster')
    op.drop_table('bestiary_monster')
    # ### end Alembic commands ###
